version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
      POSTGRES_USER: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost"]
        interval: 5s
        timeout: 5s
        retries: 20
        start_period: 10s

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    mem_limit: 512m
    cpus: 0.25
    environment:
      DATABASE_URL: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}"
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      ENVIRONMENT: ${ENVIRONMENT}
    hostname: app
    ports:
      - "8000:80"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:80/api/v1/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
